version: '3.8'

services:
  account-service:
    build:
      context: .
    restart: always
    ports:
      - "8001:80"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - default
      - gnetwork

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - default 
    volumes:
      - ../../databases/account-app/mysql/data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-server
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - default 

networks:
  gnetwork:
    name: gnetwork


